theme = "papersite-template"
languageCode = "en-us"
baseurl = "http://stackwarpattack.com/"
title = "StackWarp"

author = "StackWarp Team"
copyright = "Copyright Â© 2026, CISPA Helmholtz Center for Information Security, all rights reserved."

disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

[params]
    name = "StackWarp"
    description = "This is the site for an example attack."

    institute_street = "Stuhlsatzenhaus 5"
    institute_city = "66123 Saarbruecken"
    institute_country = "Germany"

    favicon = "favicon.ico"

[markup]
  # syntax highlight settings
  # available themes: https://xyproto.github.io/splash/docs/
  [markup.highlight]
    style = "onedark"
  # unsafe to ensure all shortcodes function correctly
  [markup.goldmark.renderer]
    unsafe= true
